data:
  path: 'data/noisy_vessel/vessel_big.tif'        # the file path for compression
  background: 0                                   # optional background intensity value used to remove empty regions before compression
  Max: 65535                                      # set according to the data bit depth: uint 16 → 65535; uint 8 → 255
  output_dirname: 'Output/vessel_split'           # output folder
  compress_method: 'BLOSC_8_shuffle_zlib'         # lossless coding method in hdf5plugin
  splitwidth: 128                                 # volume partition size
paras:
  init_step: 12                                   # initial step d, larger d leads to larger compression ratio
  loss_aim: 1e-10                                 # not used
  lr_init: 1e-1                                   # the initial learning rate
  lr_final: 1e-3                                  # the final learning rate
  iternum: 10000                                  # total number for optimization iterations
  thredhold: 1e-9                                 # default: 1
  prune_step: 500                                 # periods for RDC
  distance_scale: 2                               # default: 2
  prune_threhold: 256                             # Gaussians with intensity below this setting is removed in RDC
  prune_start_loss: 1.0e-3                        # RDC begin perform with loss below this setting
  every_n: 1                                      # default: 1
  

